trigger: 
- main
pool: 
  name: Default

steps:
- checkout : self

- script : echo "Pipeline Start"
  displayName : Start Pipeline

- script : dotnet restore
  displayName : Restore Packages

- script : dotnet build --configuration Release
  displayName : Build Application 

- script : dotnet test --no-build
  displayName: Run Unit Tests

- script : dotnet publish UseAppSettings/UseAppSettings.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: Publish Application

- script : dotnet --info
  displayName: Display .Net Information

