trigger: - main
pool: vmImage: ubuntu-latest

steps:
- checkout : self

- task : UseDotNet@2
  inputs : 
    packageType : sdk
    version : '8.0.25'

- script : dotnet restore
  displayName : Restore Packages

- script : dotnet build --configuration Release
  displayName : Build Application

echo "Pipeline Started"